example/frontend/urls.py
from django.urls import path
from django.views.generic import TemplateView
from django.utils.translation import gettext_lazy as _
from django.shortcuts import redirect
from . import views

app_name = 'frontend'

urlpatterns = [
    path('', lambda x: redirect('/page/1/'), name="index"),
    path('page/<int:page>/', views.page, name="page"),
    path('page/<int:page>/view-code/', views.code, name="code"),
]

example/others/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView
from django.utils.translation import gettext_lazy as _
from django.views.generic import TemplateView
from django.shortcuts import redirect
from . import views
from backend.models import Artist

app_name = 'others'

urlpatterns = [
    path('files_upload/', views.FileFormView.as_view(), name="files_upload"),
    path('chained_selection/', views.chained_selection, name="chained_selection"),
]

example/project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.shortcuts import redirect
from django.conf.urls.static import static
from django.conf import settings

admin.site.enable_nav_sidebar = False

urlpatterns = [
    #path('', lambda x: redirect('/files_upload/'), name='index'),
    path('', include('frontend.urls', namespace='frontend')),
    path('home/', TemplateView.as_view(template_name="pages/index.html"), name="home"),
    path('admin/', admin.site.urls),
    path('frontend_forms/', include('frontend_forms.urls', namespace='frontend_forms')),
    path('samples/', include('samples.urls', namespace='samples')),
    path('select2/', include('django_select2.urls')),
    path('others/', include('others.urls', namespace='others')),
] \
+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

example/frontend/views.py
import os
from django.shortcuts import render
from django.urls import reverse
from django.contrib import messages
from django.http import HttpResponse
from django.utils.html import escape
from django.template.loader import render_to_string


sections = [
    {
        'title': '',
        'pages': [
            {'index': 1, 'title': 'Introduction', },
        ]
    },
    {
        'title': 'Basic modals',
        'pages': [
            {'index': 2, 'title': 'HTML popup windows do not exist', },
            {'index': 3, 'title': 'A basic modal box with pure Javascript', },
            {'index': 4, 'title': 'A modal which returns a value', },
            {'index': 5, 'title': 'Bootstrap modal plugin', },
        ]
    },
    {
        'title': 'Basic modals in a Django template',
        'pages': [
            {'index': 6, 'title': 'Objectives', },
            {'index': 7, 'title': 'Usage', },
            {'index': 8, 'title': 'Opening a Dialog', },
            {'index': 9, 'title': 'Dialog methods and options', },
            {'index': 10, 'title': 'Dialog notifications', },
            {'index': 11, 'title': 'Examples', },
            {'index': 12, 'title': 'Files organization', },
        ]
    },
    {
        'title': 'Form submission from a modal',
        'pages': [
        ]
    },
    {
        'title': 'Creating or updating a Django Model in the front-end',
        'pages': [
        ]
    },
    {
        'title': 'Creating or updating a Django Model (revised)',
        'pages': [
        ]
    },
    {
        'title': 'Advanced forms',
        'pages': [
        ]
    },
    {
        'title': 'Utilities',
        'pages': [
            {'index': 100, 'title': 'Utilities', },
        ]
    },
]


def get_last_page_index():
    for i in range(len(sections)-1, -1, -1):
        section = sections[i]
        if section['pages']:
            page_index = section['pages'][-1]['index']
            return page_index
    return 0

def get_page_template_name(page):
    return "pages0/%d.html" % page

def get_page_template_path(page):
    return os.path.abspath(os.path.join('.', 'frontend', 'templates', 'pages0', '%d.html' % page
))


def page(request, page):

    def get_page_title(page_index):
        for section in sections:
            for page in section['pages']:
                if page['index'] == page_index:
                    return page['title']
        return ''

    template_name = "pages0/%d.html" % page

    return render(request, get_page_template_name(page), {
        'page_index': page,
        'page_title': get_page_title(page),
        'sections': sections,
        'previous_page': reverse('frontend:page', args=(page-1, )) if page > 1 else None,
        'next_page': reverse('frontend:page', args=(page+1, )) if page < get_last_page_index() else None,
    })


def code(request, page):
    filename = get_page_template_path(page)
    with open(filename, "r") as f:
        text = f.read()
    html = '<pre>' + escape(text) + '</pre>'
    return HttpResponse(html)

example/frontend/templates/base0.html
{% load i18n static utils_tags %}
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <meta name="description" content="">
        <meta name="author" content="Mario Orlandi - Brainstorm S.n.c.">
        <title>Frontend-forms example</title>

        <link rel='stylesheet' href="{% static 'bootstrap/dist/css/bootstrap.min.css' %}">
        <link rel='stylesheet' href="{% static 'bootstrap4-toggle/css/bootstrap4-toggle.min.css' %}">
        <link rel='stylesheet' href="{% static 'font-awesome/css/font-awesome.min.css' %}">
        <link rel='stylesheet' href="{% static 'sweetalert2/dist/sweetalert2.min.css' %}">
        <link rel='stylesheet' href="{% static 'dropzone/dist/min/dropzone.min.css' %}">
        <link rel="stylesheet" href="{% static 'frontend_forms/css/frontend_forms.css' %}">
        <link rel="stylesheet" href="{% static 'markup.css' %}">
        <link href="{% static 'pygments/styles/monokai.css' %}" media="screen" rel="stylesheet" type="text/css" />

        {# Select2 support #}
        <link rel="stylesheet" type="text/css" href="{% static 'select2/dist/css/select2.min.css' %}" />

        <link rel="stylesheet" href="{% static 'styles.css' %}">
        <link rel="stylesheet" href="{% static 'frontend.css' %}">

        {% block extrastyle %}
        {% endblock extrastyle %}

        <meta name="theme-color" content="#563d7c">

    </head>
    <body>

        {% include 'toolbar.html' %}

        <div class="container-fluid">
            <div class="row">
                {% include 'sidebar.html' %}
                <main id="main" role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4">

    <a href="https://github.com/morlandi/django-frontend-forms" style="float: right">
        <img loading="lazy" width="149" height="149"
        src="{% static 'images/forkme_right_darkblue_121621.png' %}"
        class="attachment-full size-full"
        alt="Fork me on GitHub"
        data-recalc-dims="1">
    </a>

                    {% block messages %}
                        {% if messages %}
                        <ul class="messages">
                            {% for message in messages %}
                                {% get_twitter_bootstrap_alert_msg_css_name message.tags as alert_tag %}
                                <li class="alert alert-{{ alert_tag }}">{{ message }}</li>
                            {% endfor %}
                        </ul>
                        {% endif %}
                    {% endblock messages %}

                    <div class="page">
                        <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
                            <h1 class="h2">{% block page-title %}{{ page_title }}{% endblock page-title %}</h1>
                            <a href="{% url 'frontend:code' page_index %}"><i class="fa fa-search"></i> view code</a>
                        </div>

                        {# <h2>{% block page-subtitle %}Page subtitle{% endblock page-subtitle %}</h2> #}

                        {% block page-content %}
                        {% endblock page-content %}

                        {% include 'bottom_nav.html' %}

                </main>
            </div>
        </div>

    {% block modals %}
        {% include 'frontend_forms/overlay.html' %}
        {% include 'frontend_forms/dialogs.html' %}
    {% endblock modals %}

    {% if USE_VANILLA_JS %}
    <script src="{% static 'frontend_forms/js/frontend_forms_vanilla.js' %}"></script>
    <script src="{% static 'sweetalert2/dist/sweetalert2.min.js' %}"></script>
    {% else %}
    <script src="{% static 'jquery/dist/jquery.min.js' %}"></script>
    <script src="{% static 'popper.js/dist/umd/popper.min.js' %}"></script>
    <script src="{% static 'jquery-ui-dist/jquery-ui.min.js' %}"></script>
    <script src="{% static 'bootstrap/dist/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'bootstrap4-toggle/js/bootstrap4-toggle.min.js' %}"></script>
    <script src="{% static 'gasparesganga-jquery-loading-overlay/dist/loadingoverlay.min.js' %}"></script>
    <script src="{% static 'sweetalert2/dist/sweetalert2.min.js' %}"></script>
    <script src="{% static 'promise-polyfill/dist/polyfill.min.js' %}"></script>
    <script src="{% static 'frontend_forms/js/frontend_forms.jsx' %}"></script>
    <script src="{% static 'dropzone/dist/min/dropzone.min.js' %}"></script>

    <script src="{% static 'select2/dist/js/select2.min.js' %}"></script>
    <script src="{% static 'select2/dist/js/i18n/it.js' %}"></script>
    <script>
        // "Select2 does not function properly when I use it inside a Bootstrap modal"
        // https://select2.org/troubleshooting/common-problems#select2-does-not-function-properly-when-i-use-it-inside-a-bootst
        // Do this before you initialize any of your modals
        //$.fn.modal.Constructor.prototype._enforceFocus = function() {};

        $.fn.select2.defaults.set("language", "it");
    </script>
    <script src="{% static 'django_select2/django_select2.js' %}"></script>
    {% endif %}
    <script src="{% url 'frontend_forms:javascript-catalog' %}"></script>

    <script>

        {% if not USE_VANILLA_JS %}
        $(document).ready(function() {

            $('#login_with_dialog').on('click', function(event) {
                event.preventDefault();
                var target = $(event.target);
                var url = target.attr('href');
                var logged_in = false;

                var login_dialog = new Dialog({
                    url: url,
                    width: '400px',
                    min_height: '200px',
                    title: '<i class="fa fa-sign-in"></i> Login ...',
                    button_save_label: "{% trans 'Login' %}",
                    button_close_label: "{% trans 'Close' %}",
                    callback: function(event_name, dialog, params) {
                        switch (event_name) {
                            case "submitted":
                                logged_in = true;
                                break;
                            case "closed":
                                if (logged_in) {
                                    FrontendForms.redirect('/', true);
                                }
                                break;
                        }
                    }

                });

                login_dialog.open(event);
            });

        });

        Dropzone.autoDiscover = false;
        Dropzone.prototype.filesize = function (size) {
           filesizecalculation(size)
        };

        {% endif %}


        function getCookie(name) {
            var value = '; ' + document.cookie,
                parts = value.split('; ' + name + '=');
            if (parts.length == 2) return parts.pop().split(';').shift();
        }

        function filesizecalculation(size) {
            if (size < 1024 * 1024) {
                return "<strong>" + (Math.round(Math.round(size / 1024) * 10) / 10) + " KB</strong>";
            } else if (size < 1024 * 1024 * 1024) {
                return "<strong>" + (Math.round((size / 1024 / 1024) * 10) / 10) + " MB</strong>";
            } else if (size < 1024 * 1024 * 1024 * 1024) {
                return "<strong>" + (Math.round((size / 1024 / 1024 / 1024) * 10) / 10) + " GB</strong>";
            }
        }

    </script>

    {% block extrajs %}
    {% endblock extrajs %}
    </body>

</html>

example/frontend/templates/bottom_nav.html
<style>

    #bottom-navigation {
        border-top: 1px solid #ccc;
        margin-top: 20px;
    }

    #bottom-navigation .next {
        float: right;
    }

</style>

<div id="bottom-navigation">
    {% if previous_page %}
    <a class="previous" href="{{previous_page}}">
        <i class="fa fa-arrow-left"></i>
        previous
    </a>
    {% endif %}
    {% if next_page %}
    <a class="next" href="{{next_page}}">
        next
        <i class="fa fa-arrow-right"></i>
    </a>
    {% endif %}
</div>
</div>

example/frontend/templates/sidebar.html
<nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
    <div class="sidebar-sticky pt-3">

        {% for section in sections %}
            {% if section.title %}
            <hr />
            <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
                <span>{{ section.title }}</span>
            </h6>
            {% endif %}
            <ul class="nav flex-column">
                {% for page in section.pages %}
                <li class="nav-item">
                    <a class="nav-link{% if page_index == page.index %} active{% endif %}" href="{% url 'frontend:page' page.index %}">
                        -&nbsp;{{ page.title }}
                    </a>
                </li>
                {% endfor %}
            </ul>
        {% endfor %}

        <hr />
        <li class="nav-item">
            <a class="nav-link" href="{% url 'home' %}">
                Old site
            </a>
        </li>

        {% if USE_VANILLA_JS %}
        <hr />
        <li class="nav-link" style = "color: orange">Now using vanilla JS</li>
        {% endif %}
    </div>
</nav>

example/frontend/templates/toolbar.html
<nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
    <a class="navbar-brand col-md-3 col-lg-2 mr-0 px-3" href="{% url 'frontend:index' %}">django-frontend-forms</a>
    <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-toggle="collapse" data-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    {# <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search"> #}
    <ul class="navbar-nav px-3">
        <li class="nav-item text-nowrap">
            <a class="nav-link" href="#">Sign out</a>
        </li>
    </ul>
</nav>