example/others/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView
from django.utils.translation import gettext_lazy as _
from django.views.generic import TemplateView
from django.shortcuts import redirect
from . import views
from backend.models import Artist

app_name = 'others'

urlpatterns = [
    path('files_upload/', views.FileFormView.as_view(), name="files_upload"),
    path('chained_selection/', views.chained_selection, name="chained_selection"),
]

example/project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.shortcuts import redirect
from django.conf.urls.static import static
from django.conf import settings

admin.site.enable_nav_sidebar = False

urlpatterns = [
    #path('', lambda x: redirect('/files_upload/'), name='index'),
    path('', include('frontend.urls', namespace='frontend')),
    path('home/', TemplateView.as_view(template_name="pages/index.html"), name="home"),
    path('admin/', admin.site.urls),
    path('frontend_forms/', include('frontend_forms.urls', namespace='frontend_forms')),
    path('samples/', include('samples.urls', namespace='samples')),
    path('select2/', include('django_select2.urls')),
    path('others/', include('others.urls', namespace='others')),
] \
+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

example/samples/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView
from django.utils.translation import gettext_lazy as _
from django.views.generic import TemplateView
from django.shortcuts import redirect
from . import views
from backend.models import Artist

app_name = 'samples'

urlpatterns = [
    path('basic-modal/',
        TemplateView.as_view(template_name="samples/basic_modal.html"),
        name="basic-modal"),
    path('basic-modal-which-returns-a-value/',
        TemplateView.as_view(template_name="samples/basic_modal_which_returns_a_value.html"),
        name="basic-modal-which-returns-a-value"),
    path('basic-modal-with-bootstrap/',
        TemplateView.as_view(template_name="samples/basic_modal_with_bootstrap.html"),
        name="basic-modal-with-bootstrap"),

    path('simple-dialogs/',
        TemplateView.as_view(template_name="samples/simple_dialogs.html"),
        name="simple-dialogs"),
    path('simple-content', views.simple_content, name="simple-content"),
    path('simple-content-forbidden', views.simple_content_forbidden, name="simple-content-forbidden"),
    path('simple-content2', views.simple_content2, name="simple-content2"),

    path('form-submission/',
        TemplateView.as_view(template_name="samples/form_submission.html"),
        name="form-submission"),
    path('edit-a-django-model-basic/',
        TemplateView.as_view(
            template_name="samples/edit_a_django_model_basic.html",
            get_context_data=lambda: {'artists': Artist.objects.all()},
        ),
        name="edit-a-django-model-basic"),
    path('edit-a-django-model-revised/',
        TemplateView.as_view(
            template_name="samples/edit_a_django_model_revised.html",
            get_context_data=lambda: {'artists': Artist.objects.all()},
        ),
        name="edit-a-django-model-revised"),
    path('form-advanced/',
        TemplateView.as_view(template_name="samples/form_advanced.html"),
        name="form-advanced"),

    path('simple-form-validation', views.simple_form_validation, name="simple-form-validation"),
    path('advanced-form-validation', views.advanced_form_validation, name="advanced-form-validation"),
    path('form-validation-with-feedback', views.form_validation_with_feedback, name="form-validation-with-feedback"),
    path('form-validation-with-json-result', views.form_validation_with_json_result, name="form-validation-with-json-result"),
    path('simple-form-validation-with-addon', views.simple_form_validation_with_addon, name="simple-form-validation-with-addon"),

    path('artist/add-basic/', views.add_artist, name="artist-add-basic"),
    path('artist/<uuid:pk>/change-basic/', views.update_artist, name="artist-change-basic"),

    path('artist/add/', views.edit_artist, name="artist-add"),
    path('artist/<uuid:pk>/change/', views.edit_artist, name="artist-change"),
    path('artist/<uuid:pk>/delete/', views.delete_artist, name="artist-delete"),

    path('new-track', views.new_track, name="new-track"),
    path('new-track-ex', views.new_track_ex, name="new-track-ex"),
]

example/samples/models.py
from django.db import models

# Create your models here.

example/samples/views.py
import time
from django.shortcuts import render
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.http import JsonResponse
from django.contrib import messages
from django.urls import reverse
from django.core.exceptions import PermissionDenied
from django.conf import settings
from frontend_forms.decorators import check_logged_in
from frontend_forms.utils import get_object_by_uuid_or_404
from backend.models import Artist
from .forms import SimpleForm
from .forms import AdvancedForm
from .forms import ArtistCreateForm
from .forms import ArtistUpdateForm
from .forms import ArtistEditForm
from .forms import TrackForm
from .forms import TrackFormEx


def is_ajax(request):
    try:
        is_ajax_request = request.accepts("application/json")
    except AttributeError as e:
        # Django < 4.0
        is_ajax_request = is_ajax(request)
    return is_ajax_request


def simulate_network_latency():
    if settings.DEBUG:
        time.sleep(1.0)


def simple_content(request):
    return HttpResponse('<b>Lorem ipsum dolor sit amet</b>, consectetur adipiscing elit. Proin dignissim dapibus ipsum id elementum. Morbi in justo purus. Duis ornare lobortis nisl eget condimentum. Donec quis lorem nec sapien vehicula eleifend vel sit amet nunc.')


def simple_content_forbidden(request):
    raise PermissionDenied


def simple_content2(request):
    # Either render only the modal content, or a full standalone page
    if is_ajax(request):
        template_name = 'dialogs/simple_content2_inner.html'
    else:
        template_name = 'dialogs/simple_content2.html'
    return render(request, template_name, {
    })


def simple_form_validation(request):

    simulate_network_latency()

    if is_ajax(request):
        template_name = 'dialogs/simple_form_inner.html'
    else:
        template_name = 'dialogs/simple_form.html'

    if request.method == 'POST':
        form = SimpleForm(data=request.POST)
        if form.is_valid():
            form.save()
            if not is_ajax(request):
                messages.info(request, "Form has been validated" )
    else:
        form = SimpleForm()

    return render(request, template_name, {
        'action': reverse('samples:simple-form-validation'),
        'form': form,
    })


def advanced_form_validation(request):

    simulate_network_latency()

    if is_ajax(request):
        template_name = 'dialogs/advanced_form_inner.html'
    else:
        template_name = 'dialogs/advanced_form.html'

    if request.method == 'POST':
        form = AdvancedForm(data=request.POST)
        if form.is_valid():
            form.save()
            if not is_ajax(request):
                messages.info(request, "Form has been validated" )
    else:
        form = AdvancedForm()

    return render(request, template_name, {
        'form': form,
    })


def form_validation_with_feedback(request):

    simulate_network_latency()

    if is_ajax(request):
        template_name = 'dialogs/simple_form_inner.html'
    else:
        template_name = 'dialogs/simple_form.html'

    if request.method == 'POST':
        form = SimpleForm(data=request.POST)
        if form.is_valid():
            form.save()
            if not is_ajax(request):
                messages.info(request, "Form has been validated")
            else:
                return HttpResponse("<h1>Great !</h1> Your form has been validated")
    else:
        form = SimpleForm()

    return render(request, template_name, {
        'action': reverse('samples:form-validation-with-feedback'),
        'form': form,
    })


def form_validation_with_json_result(request):

    simulate_network_latency()

    if is_ajax(request):
        template_name = 'dialogs/simple_form_inner.html'
    else:
        template_name = 'dialogs/simple_form.html'

    if request.method == 'POST':
        form = SimpleForm(data=request.POST)
        if form.is_valid():
            form.save()
            if not is_ajax(request):
                messages.info(request, "Form has been validated")
            else:
                return JsonResponse(form.cleaned_data)
    else:
        form = SimpleForm()

    return render(request, template_name, {
        'action': reverse('samples:form-validation-with-json-result'),
        'form': form,
    })


def simple_form_validation_with_addon(request):

    simulate_network_latency()

    if is_ajax(request):
        template_name = 'dialogs/simple_form_with_addon_inner.html'
    else:
        template_name = 'dialogs/simple_form_with_addon.html'

    if request.method == 'POST':
        form = SimpleForm(data=request.POST)
        if form.is_valid():
            form.save()
            if not is_ajax(request):
                messages.info(request, "Form has been validated" )
    else:
        form = SimpleForm()

    return render(request, template_name, {
        'action': reverse('samples:simple-form-validation-with-addon'),
        'form': form,
    })


@check_logged_in()
def add_artist(request):

    if not request.user.has_perm('backend.add_artist'):
        raise PermissionDenied

    # Either render only the modal content, or a full standalone page
    if is_ajax(request):
        template_name = 'frontend_forms/generic_form_inner.html'
    else:
        template_name = 'dialogs/generic_form.html'

    object = None
    if request.method == 'POST':

        simulate_network_latency()

        form = ArtistCreateForm(data=request.POST)
        if form.is_valid():
            object = form.save()
            if not is_ajax(request):
                # reload the page
                message = 'The object "%s" was added successfully.' % object
                messages.success(request, message)
                next = request.META['PATH_INFO']
                return HttpResponseRedirect(next)
            # if is_ajax(), we just return the validated form, so the modal will close
    else:
        form = ArtistCreateForm()

    return render(request, template_name, {
        'form': form,
        'object': object,
    })


@check_logged_in()
def update_artist(request, pk):

    if not request.user.has_perm('backend.change_artist'):
        raise PermissionDenied

    # Either render only the modal content, or a full standalone page
    if is_ajax(request):
        template_name = 'frontend_forms/generic_form_inner.html'
    else:
        template_name = 'dialogs/generic_form.html'

    object = get_object_by_uuid_or_404(Artist, pk)
    if request.method == 'POST':

        simulate_network_latency()

        form = ArtistUpdateForm(instance=object, data=request.POST)
        if form.is_valid():
            object = form.save()
            if not is_ajax(request):
                # reload the page
                message = 'The object "%s" was changed successfully.' % object
                messages.success(request, message)
                next = request.META['PATH_INFO']
                return HttpResponseRedirect(next)
            # if is_ajax(), we just return the validated form, so the modal will close
    else:
        form = ArtistUpdateForm(instance=object)

    return render(request, template_name, {
        'form': form,
        'object': object,
    })


@check_logged_in()
def edit_artist(request, pk=None):
    """
    Either add a new Artist,
    or change an existing one
    """

    # Retrieve object
    if pk is None:
        # "Add" mode
        object = None
        required_permission = 'backend.add_artist'
    else:
        # "Change" mode
        object = get_object_by_uuid_or_404(Artist, pk)
        required_permission = 'backend.change_artist'

    # Check user permissions
    if not request.user.is_authenticated or not request.user.has_perm(required_permission):
        raise PermissionDenied


    # Either render only the modal content, or a full standalone page
    if is_ajax(request):
        template_name = 'frontend_forms/generic_form_inner.html'
    else:
        template_name = 'dialogs/generic_form.html'

    if request.method == 'POST':

        simulate_network_latency()

        form = ArtistEditForm(instance=object, data=request.POST)
        if form.is_valid():
            object = form.save()
            if not is_ajax(request):
                # reload the page
                if pk is None:
                    message = 'The object "%s" was added successfully.' % object
                else:
                    message = 'The object "%s" was changed successfully.' % object
                messages.success(request, message)
                next = request.META['PATH_INFO']
                return HttpResponseRedirect(next)
            # if is_ajax(), we just return the validated form, so the modal will close
    else:
        form = ArtistEditForm(instance=object)

    return render(request, template_name, {
        'form': form,
        'object': object,
    })


def delete_artist(request, pk):

    required_permission = 'backend.delete_artist'
    if not request.user.is_authenticated or not request.user.has_perm(required_permission):
        raise PermissionDenied

    object = get_object_by_uuid_or_404(Artist, pk)
    object_id = object.id
    object.delete()

    return JsonResponse({'object_id': object_id})


def new_track(request):

    simulate_network_latency()

    if is_ajax(request):
        template_name = 'dialogs/track_form_inner.html'
    else:
        template_name = 'dialogs/track_form.html'

    if request.method == 'POST':
        form = TrackForm(data=request.POST)
        if form.is_valid():
            #form.save()
            if not is_ajax(request):
                messages.info(request, "Form has been validated")
            else:
                return HttpResponse(
                    '<h1>Great !</h1> Your form has been validated<br /><br />You entered <b>"%s"</b>' % form.cleaned_data['name']
                )
    else:
        form = TrackForm()

    #action = request.get_full_path()

example/samples/templates/dialogs/advanced_form.html
{% extends "base.html" %}
{% load static i18n %}


{% block content %}
{% include 'dialogs/advanced_form_inner.html' %}
{% endblock content %}


{% block extrastyle %}
<style>
    form {
        max-width: 400px;
        border: 1px solid black;
        padding: 40px;
    }
</style>
{% endblock extrastyle %}


{% block extrajs %}
<script>
    $(document).ready(function() {
        $("form .datepicker").datepicker({});
    });
</script>
{% endblock extrajs %}

example/samples/templates/dialogs/advanced_form_inner.html
{% load i18n frontend_forms_tags %}


<form action="{% url 'samples:advanced-form-validation' %}" method="post" class="form" novalidate>
    {% csrf_token %}
    {% render_form form %}
    <div class="form-group form-submit-row">
        <button type="submit" class="btn btn-lg btn-primary btn-block">{% trans 'Submit' %}</button>
    </div>
</form>

example/samples/templates/dialogs/generic_form.html
{% extends "base.html" %}
{% load static i18n %}

{% block content %}
{% include 'frontend_forms/generic_form_inner.html' %}
{% endblock content %}

{% block extrastyle %}
<style>
    form {
        max-width: 400px;
        border: 1px solid black;
        padding: 40px;
    }
</style>
{% endblock extrastyle %}

example/samples/templates/dialogs/simple_content2.html
{% extends "base.html" %}
{% load static i18n %}

{% block content %}
{% include 'dialogs/simple_content2_inner.html' %}
{% endblock content %}

example/samples/templates/dialogs/simple_content2_inner.html
<div class="row">
    <div class="col-sm-4">
        {% lorem 1 p random %}
    </div>
    <div class="col-sm-4">
        {% lorem 1 p random %}
    </div>
    <div class="col-sm-4">
        {% lorem 1 p random %}
    </div>
</div>

example/samples/templates/dialogs/simple_form.html
{% extends "base.html" %}
{% load static i18n %}

{% block content %}
{% include 'dialogs/simple_form_inner.html' %}
{% endblock content %}

{% block extrastyle %}
<style>
    form {
        max-width: 400px;
        border: 1px solid black;
        padding: 40px;
    }
</style>
{% endblock extrastyle %}

example/samples/templates/dialogs/simple_form_inner.html
{% load i18n frontend_forms_tags %}


<form action="{{ action }}" method="post" class="form" novalidate>
    {% csrf_token %}
    {% render_form form %}
    <div class="form-group form-submit-row">
        <button type="submit" class="btn btn-lg btn-primary btn-block">{% trans 'Submit' %}</button>
    </div>
</form>

example/samples/templates/dialogs/simple_form_with_addon.html
{% extends "base.html" %}
{% load static i18n %}

{% block content %}
{% include 'dialogs/simple_form_inner_with_addon.html' %}
{% endblock content %}

{% block extrastyle %}
<style>
    form {
        max-width: 400px;
        border: 1px solid black;
        padding: 40px;
    }
</style>
{% endblock extrastyle %}

example/samples/templates/dialogs/simple_form_with_addon_inner.html
{% load i18n frontend_forms_tags %}


{% comment %}
<form action="{{ action }}" method="post" class="form" novalidate>
    {% csrf_token %}
    {% render_form form %}
    <div class="form-group form-submit-row">
        <button type="submit" class="btn btn-lg btn-primary btn-block">{% trans 'Submit' %}</button>
    </div>
</form>
{% endcomment %}


<form method="post">
    {% csrf_token %}

    {% if form.non_field_errors %}
        <ul class="errorlist">
            {% for error in form.non_field_errors %}
                <li>{{ error }}</li>
            {% endfor %}
        </ul>
    {% endif %}

    {% for hidden_field in form.hidden_fields %}
        {{ hidden_field }}
    {% endfor %}

    <fieldset>
        {% render_form_field form.value addon='<i class="fa fa-flask"></i>' %}
    </fieldset>

    <div class="form-group form-submit-row">
        <button type="submit" class="btn btn-lg btn-primary btn-block">{% trans 'Submit' %}</button>
    </div>
</form>

example/samples/templates/dialogs/track_form.html
{% extends "base.html" %}
{% load static i18n %}

{% block content %}
{% include 'dialogs/track_form_inner.html' %}
{% endblock content %}

{% block extrastyle %}
<style>
    form {
        max-width: 400px;
        border: 1px solid black;
        padding: 40px;
    }
</style>
{% endblock extrastyle %}

example/samples/templates/dialogs/track_form_ex.html
{% extends "base.html" %}
{% load static i18n %}


{% block extrajs %}
    <script src="{% static 'admin/js/jquery.init.js' %}"></script>
    <script src="{% static 'admin/js/admin/RelatedObjectLookups.js' %}"></script>
{% endblock extrajs %}


{% block content %}

<h3>Replicating Django’s admin form popups</h3>

Adapted from: <a href="https://www.hoboes.com/Mimsy/hacks/replicating-djangos-admin/">https://www.hoboes.com/Mimsy/hacks/replicating-djangos-admin/</a>

<br />
See also:<br />
- <a href="https://stackoverflow.com/questions/5744480/django-admin-relatedobjectlookups-how-does-it-refresh-and-set-the-select-on">Django Admin - RelatedObjectLookups - How Does it refresh and set the select on the parent window?</a><br />
- <a href="https://stackoverflow.com/questions/2347582/django-admin-popup-functionality">Django Admin popup functionality</a><br />

{% include 'dialogs/track_form_ex_inner.html' %}
{% endblock content %}

{% block extrastyle %}
<style>
    form {
        max-width: 400px;
        border: 1px solid black;
        padding: 40px;
    }
</style>
{% endblock extrastyle %}

example/samples/templates/dialogs/track_form_ex_inner.html
{% load i18n frontend_forms_tags %}

{# Not required, but harmless #}
{{ form.media }}

<form method="post" class="form" novalidate>
    {% csrf_token %}
    {% render_form form %}

    <div class="form-group form-submit-row">
        <button type="submit" class="btn btn-lg btn-primary btn-block">{% trans 'Submit' %}</button>
    </div>
</form>

example/samples/templates/dialogs/track_form_inner.html
{% load i18n frontend_forms_tags %}

{# Not required, but harmless #}
{{ form.media }}

<form method="post" class="form" novalidate>
    {% csrf_token %}
    {% render_form form %}
    <div class="form-group form-submit-row">
        <button type="submit" class="btn btn-lg btn-primary btn-block">{% trans 'Submit' %}</button>
    </div>
</form>