example/others/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView
from django.utils.translation import gettext_lazy as _
from django.views.generic import TemplateView
from django.shortcuts import redirect
from . import views
from backend.models import Artist

app_name = 'others'

urlpatterns = [
    path('files_upload/', views.FileFormView.as_view(), name="files_upload"),
    path('chained_selection/', views.chained_selection, name="chained_selection"),
]

example/project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.shortcuts import redirect
from django.conf.urls.static import static
from django.conf import settings

admin.site.enable_nav_sidebar = False

urlpatterns = [
    #path('', lambda x: redirect('/files_upload/'), name='index'),
    path('', include('frontend.urls', namespace='frontend')),
    path('home/', TemplateView.as_view(template_name="pages/index.html"), name="home"),
    path('admin/', admin.site.urls),
    path('frontend_forms/', include('frontend_forms.urls', namespace='frontend_forms')),
    path('samples/', include('samples.urls', namespace='samples')),
    path('select2/', include('django_select2.urls')),
    path('others/', include('others.urls', namespace='others')),
] \
+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

example/project/templates/base.html
{% load i18n static %}

<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel='stylesheet' href="{% static 'bootstrap/dist/css/bootstrap.min.css' %}">
    <link rel='stylesheet' href="{% static 'bootstrap4-toggle/css/bootstrap4-toggle.min.css' %}">
    <link rel='stylesheet' href="{% static 'font-awesome/css/font-awesome.min.css' %}">
    <link rel='stylesheet' href="{% static 'sweetalert2/dist/sweetalert2.min.css' %}">
    <link rel='stylesheet' href="{% static 'dropzone/dist/min/dropzone.min.css' %}">
    <link rel="stylesheet" href="{% static 'frontend_forms/css/frontend_forms.css' %}">
    <link rel="stylesheet" href="{% static 'example.css' %}">
    <link rel="stylesheet" href="{% static 'markup.css' %}">
    <link href="{% static 'pygments/styles/monokai.css' %}" media="screen" rel="stylesheet" type="text/css" />

    {# Select2 support #}
    <link rel="stylesheet" type="text/css" href="{% static 'select2/dist/css/select2.min.css' %}" />

    {% block extrastyle %}
    {% endblock extrastyle %}

</head>

<body class="page-{% block body-class%}{% endblock body-class%}">

    <a href="https://github.com/morlandi/django-frontend-forms" style="float: right">
        <img loading="lazy" width="149" height="149"
        src="{% static 'images/forkme_right_darkblue_121621.png' %}"
        class="attachment-full size-full"
        alt="Fork me on GitHub"
        data-recalc-dims="1">
    </a>

    {% include 'navbar.html' %}

    <main role="main" class="container">

        <div id="page-title"><h2>{% block page-title %}{% endblock page-title %}</h2></div>

        {% block messages %}
            {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <li class="{{message.tag}}">{{ message }}</li>
                {% endfor %}
            </ul>
            {% endif %}
        {% endblock messages %}

        <div id="content">
        {% block content %}
            <h1>Content goes here</h1>
        {% endblock content %}
        </div>

    </main>

    {% block modals %}
        {% include 'frontend_forms/dialogs.html' %}
    {% endblock modals %}

    {% if USE_VANILLA_JS %}
    <script src="{% static 'frontend_forms/js/frontend_forms_vanilla.js' %}"></script>
    <script src="{% static 'sweetalert2/dist/sweetalert2.min.js' %}"></script>
    {% else %}
    <script src="{% static 'jquery/dist/jquery.min.js' %}"></script>
    <script src="{% static 'popper.js/dist/umd/popper.min.js' %}"></script>
    <script src="{% static 'jquery-ui-dist/jquery-ui.min.js' %}"></script>
    <script src="{% static 'bootstrap/dist/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'bootstrap4-toggle/js/bootstrap4-toggle.min.js' %}"></script>
    <script src="{% static 'gasparesganga-jquery-loading-overlay/dist/loadingoverlay.min.js' %}"></script>
    <script src="{% static 'sweetalert2/dist/sweetalert2.min.js' %}"></script>
    <script src="{% static 'promise-polyfill/dist/polyfill.min.js' %}"></script>
    <script src="{% static 'frontend_forms/js/frontend_forms.jsx' %}"></script>
    <script src="{% static 'dropzone/dist/min/dropzone.min.js' %}"></script>

    <script src="{% static 'select2/dist/js/select2.min.js' %}"></script>
    <script src="{% static 'select2/dist/js/i18n/it.js' %}"></script>
    <script>
        // "Select2 does not function properly when I use it inside a Bootstrap modal"
        // https://select2.org/troubleshooting/common-problems#select2-does-not-function-properly-when-i-use-it-inside-a-bootst
        // Do this before you initialize any of your modals
        //$.fn.modal.Constructor.prototype._enforceFocus = function() {};

        $.fn.select2.defaults.set("language", "it");
    </script>
    <script src="{% static 'django_select2/django_select2.js' %}"></script>
    {% endif %}

    <script src="{% url 'frontend_forms:javascript-catalog' %}"></script>

    <script>

        {% if not USE_VANILLA_JS %}
        $(document).ready(function() {

            $('#login_with_dialog').on('click', function(event) {
                event.preventDefault();
                var target = $(event.target);
                var url = target.attr('href');
                var logged_in = false;

                var login_dialog = new Dialog({
                    url: url,
                    width: '400px',
                    min_height: '200px',
                    title: '<i class="fa fa-sign-in"></i> Login ...',
                    button_save_label: "{% trans 'Login' %}",
                    button_close_label: "{% trans 'Close' %}",
                    callback: function(event_name, dialog, params) {
                        switch (event_name) {
                            case "submitted":
                                logged_in = true;
                                break;
                            case "closed":
                                if (logged_in) {
                                    FrontendForms.redirect('/', true);
                                }
                                break;
                        }
                    }

                });

                login_dialog.open(event);
            });

        });

        Dropzone.autoDiscover = false;
        Dropzone.prototype.filesize = function (size) {
           filesizecalculation(size)
        };
        {% endif %}

        function getCookie(name) {
            var value = '; ' + document.cookie,
                parts = value.split('; ' + name + '=');
            if (parts.length == 2) return parts.pop().split(';').shift();
        }

        function filesizecalculation(size) {
            if (size < 1024 * 1024) {
                return "<strong>" + (Math.round(Math.round(size / 1024) * 10) / 10) + " KB</strong>";
            } else if (size < 1024 * 1024 * 1024) {
                return "<strong>" + (Math.round((size / 1024 / 1024) * 10) / 10) + " MB</strong>";
            } else if (size < 1024 * 1024 * 1024 * 1024) {
                return "<strong>" + (Math.round((size / 1024 / 1024 / 1024) * 10) / 10) + " GB</strong>";
            }
        }

    </script>

    {% block extrajs %}
    {% endblock extrajs %}

</body>

</html>

example/project/templates/navbar.html
{% load i18n %}

<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
    <a class="navbar-brand" href="/">django-frontend-forms example</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
            {% comment %}
            <li class="nav-item">
                <a class="nav-link page-index" href="{% url 'others:files_upload' %}">{% trans 'Files upload' %}</a>
            </li>
            <li class="nav-item">
                <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
            </li>
            {% endcomment %}
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{% trans 'Others' %}</a>
                <div class="dropdown-menu" aria-labelledby="dropdown01">
                    <a class="dropdown-item" href="{% url 'others:files_upload' %}">{% trans 'Files upload' %}</a>
                    <a class="dropdown-item" href="{% url 'others:chained_selection' %}">{% trans 'Chained selection' %}</a>
                </div>
            </li>
        </ul>
        <ul class="navbar-nav my-2 my-lg-0">
            {% if request.user.is_authenticated %}
                <li class="nav-item">
                    <span class="nav-link">({{request.user}})</span>
                </li>
                <li class="nav-item">
                    <a href="{% url 'frontend_forms:logout' %}" class="nav-link">{% trans 'Logout' %}</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a href="{% url 'frontend_forms:login' %}" class="nav-link">{% trans 'Login (standalone)' %}</a>
                </li>
                <li class="nav-item">
                    <a id="login_with_dialog" href="{% url 'frontend_forms:login' %}" class="nav-link">{% trans 'Login (popup)' %}
                    </a>
                </li>
            {% endif %}
            </li>
        </ul>
        {% comment %}
        <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
            <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
        </form>
        {% endcomment %}
    </div>
</nav>