example/others/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView
from django.utils.translation import gettext_lazy as _
from django.views.generic import TemplateView
from django.shortcuts import redirect
from . import views
from backend.models import Artist

app_name = 'others'

urlpatterns = [
    path('files_upload/', views.FileFormView.as_view(), name="files_upload"),
    path('chained_selection/', views.chained_selection, name="chained_selection"),
]

example/project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.shortcuts import redirect
from django.conf.urls.static import static
from django.conf import settings

admin.site.enable_nav_sidebar = False

urlpatterns = [
    #path('', lambda x: redirect('/files_upload/'), name='index'),
    path('', include('frontend.urls', namespace='frontend')),
    path('home/', TemplateView.as_view(template_name="pages/index.html"), name="home"),
    path('admin/', admin.site.urls),
    path('frontend_forms/', include('frontend_forms.urls', namespace='frontend_forms')),
    path('samples/', include('samples.urls', namespace='samples')),
    path('select2/', include('django_select2.urls')),
    path('others/', include('others.urls', namespace='others')),
] \
+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

example/samples/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView
from django.utils.translation import gettext_lazy as _
from django.views.generic import TemplateView
from django.shortcuts import redirect
from . import views
from backend.models import Artist

app_name = 'samples'

urlpatterns = [
    path('basic-modal/',
        TemplateView.as_view(template_name="samples/basic_modal.html"),
        name="basic-modal"),
    path('basic-modal-which-returns-a-value/',
        TemplateView.as_view(template_name="samples/basic_modal_which_returns_a_value.html"),
        name="basic-modal-which-returns-a-value"),
    path('basic-modal-with-bootstrap/',
        TemplateView.as_view(template_name="samples/basic_modal_with_bootstrap.html"),
        name="basic-modal-with-bootstrap"),

    path('simple-dialogs/',
        TemplateView.as_view(template_name="samples/simple_dialogs.html"),
        name="simple-dialogs"),
    path('simple-content', views.simple_content, name="simple-content"),
    path('simple-content-forbidden', views.simple_content_forbidden, name="simple-content-forbidden"),
    path('simple-content2', views.simple_content2, name="simple-content2"),

    path('form-submission/',
        TemplateView.as_view(template_name="samples/form_submission.html"),
        name="form-submission"),
    path('edit-a-django-model-basic/',
        TemplateView.as_view(
            template_name="samples/edit_a_django_model_basic.html",
            get_context_data=lambda: {'artists': Artist.objects.all()},
        ),
        name="edit-a-django-model-basic"),
    path('edit-a-django-model-revised/',
        TemplateView.as_view(
            template_name="samples/edit_a_django_model_revised.html",
            get_context_data=lambda: {'artists': Artist.objects.all()},
        ),
        name="edit-a-django-model-revised"),
    path('form-advanced/',
        TemplateView.as_view(template_name="samples/form_advanced.html"),
        name="form-advanced"),

    path('simple-form-validation', views.simple_form_validation, name="simple-form-validation"),
    path('advanced-form-validation', views.advanced_form_validation, name="advanced-form-validation"),
    path('form-validation-with-feedback', views.form_validation_with_feedback, name="form-validation-with-feedback"),
    path('form-validation-with-json-result', views.form_validation_with_json_result, name="form-validation-with-json-result"),
    path('simple-form-validation-with-addon', views.simple_form_validation_with_addon, name="simple-form-validation-with-addon"),

    path('artist/add-basic/', views.add_artist, name="artist-add-basic"),
    path('artist/<uuid:pk>/change-basic/', views.update_artist, name="artist-change-basic"),

    path('artist/add/', views.edit_artist, name="artist-add"),
    path('artist/<uuid:pk>/change/', views.edit_artist, name="artist-change"),
    path('artist/<uuid:pk>/delete/', views.delete_artist, name="artist-delete"),

    path('new-track', views.new_track, name="new-track"),
    path('new-track-ex', views.new_track_ex, name="new-track-ex"),
]

example/samples/models.py
from django.db import models

# Create your models here.

example/samples/views.py
import time
from django.shortcuts import render
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.http import JsonResponse
from django.contrib import messages
from django.urls import reverse
from django.core.exceptions import PermissionDenied
from django.conf import settings
from frontend_forms.decorators import check_logged_in
from frontend_forms.utils import get_object_by_uuid_or_404
from backend.models import Artist
from .forms import SimpleForm
from .forms import AdvancedForm
from .forms import ArtistCreateForm
from .forms import ArtistUpdateForm
from .forms import ArtistEditForm
from .forms import TrackForm
from .forms import TrackFormEx


def is_ajax(request):
    try:
        is_ajax_request = request.accepts("application/json")
    except AttributeError as e:
        # Django < 4.0
        is_ajax_request = is_ajax(request)
    return is_ajax_request


def simulate_network_latency():
    if settings.DEBUG:
        time.sleep(1.0)


def simple_content(request):
    return HttpResponse('<b>Lorem ipsum dolor sit amet</b>, consectetur adipiscing elit. Proin dignissim dapibus ipsum id elementum. Morbi in justo purus. Duis ornare lobortis nisl eget condimentum. Donec quis lorem nec sapien vehicula eleifend vel sit amet nunc.')


def simple_content_forbidden(request):
    raise PermissionDenied


def simple_content2(request):
    # Either render only the modal content, or a full standalone page
    if is_ajax(request):
        template_name = 'dialogs/simple_content2_inner.html'
    else:
        template_name = 'dialogs/simple_content2.html'
    return render(request, template_name, {
    })


def simple_form_validation(request):

    simulate_network_latency()

    if is_ajax(request):
        template_name = 'dialogs/simple_form_inner.html'
    else:
        template_name = 'dialogs/simple_form.html'

    if request.method == 'POST':
        form = SimpleForm(data=request.POST)
        if form.is_valid():
            form.save()
            if not is_ajax(request):
                messages.info(request, "Form has been validated" )
    else:
        form = SimpleForm()

    return render(request, template_name, {
        'action': reverse('samples:simple-form-validation'),
        'form': form,
    })


def advanced_form_validation(request):

    simulate_network_latency()

    if is_ajax(request):
        template_name = 'dialogs/advanced_form_inner.html'
    else:
        template_name = 'dialogs/advanced_form.html'

    if request.method == 'POST':
        form = AdvancedForm(data=request.POST)
        if form.is_valid():
            form.save()
            if not is_ajax(request):
                messages.info(request, "Form has been validated" )
    else:
        form = AdvancedForm()

    return render(request, template_name, {
        'form': form,
    })


def form_validation_with_feedback(request):

    simulate_network_latency()

    if is_ajax(request):
        template_name = 'dialogs/simple_form_inner.html'
    else:
        template_name = 'dialogs/simple_form.html'

    if request.method == 'POST':
        form = SimpleForm(data=request.POST)
        if form.is_valid():
            form.save()
            if not is_ajax(request):
                messages.info(request, "Form has been validated")
            else:
                return HttpResponse("<h1>Great !</h1> Your form has been validated")
    else:
        form = SimpleForm()

    return render(request, template_name, {
        'action': reverse('samples:form-validation-with-feedback'),
        'form': form,
    })


def form_validation_with_json_result(request):

    simulate_network_latency()

    if is_ajax(request):
        template_name = 'dialogs/simple_form_inner.html'
    else:
        template_name = 'dialogs/simple_form.html'

    if request.method == 'POST':
        form = SimpleForm(data=request.POST)
        if form.is_valid():
            form.save()
            if not is_ajax(request):
                messages.info(request, "Form has been validated")
            else:
                return JsonResponse(form.cleaned_data)
    else:
        form = SimpleForm()

    return render(request, template_name, {
        'action': reverse('samples:form-validation-with-json-result'),
        'form': form,
    })


def simple_form_validation_with_addon(request):

    simulate_network_latency()

    if is_ajax(request):
        template_name = 'dialogs/simple_form_with_addon_inner.html'
    else:
        template_name = 'dialogs/simple_form_with_addon.html'

    if request.method == 'POST':
        form = SimpleForm(data=request.POST)
        if form.is_valid():
            form.save()
            if not is_ajax(request):
                messages.info(request, "Form has been validated" )
    else:
        form = SimpleForm()

    return render(request, template_name, {
        'action': reverse('samples:simple-form-validation-with-addon'),
        'form': form,
    })


@check_logged_in()
def add_artist(request):

    if not request.user.has_perm('backend.add_artist'):
        raise PermissionDenied

    # Either render only the modal content, or a full standalone page
    if is_ajax(request):
        template_name = 'frontend_forms/generic_form_inner.html'
    else:
        template_name = 'dialogs/generic_form.html'

    object = None
    if request.method == 'POST':

        simulate_network_latency()

        form = ArtistCreateForm(data=request.POST)
        if form.is_valid():
            object = form.save()
            if not is_ajax(request):
                # reload the page
                message = 'The object "%s" was added successfully.' % object
                messages.success(request, message)
                next = request.META['PATH_INFO']
                return HttpResponseRedirect(next)
            # if is_ajax(), we just return the validated form, so the modal will close
    else:
        form = ArtistCreateForm()

    return render(request, template_name, {
        'form': form,
        'object': object,
    })


@check_logged_in()
def update_artist(request, pk):

    if not request.user.has_perm('backend.change_artist'):
        raise PermissionDenied

    # Either render only the modal content, or a full standalone page
    if is_ajax(request):
        template_name = 'frontend_forms/generic_form_inner.html'
    else:
        template_name = 'dialogs/generic_form.html'

    object = get_object_by_uuid_or_404(Artist, pk)
    if request.method == 'POST':

        simulate_network_latency()

        form = ArtistUpdateForm(instance=object, data=request.POST)
        if form.is_valid():
            object = form.save()
            if not is_ajax(request):
                # reload the page
                message = 'The object "%s" was changed successfully.' % object
                messages.success(request, message)
                next = request.META['PATH_INFO']
                return HttpResponseRedirect(next)
            # if is_ajax(), we just return the validated form, so the modal will close
    else:
        form = ArtistUpdateForm(instance=object)

    return render(request, template_name, {
        'form': form,
        'object': object,
    })


@check_logged_in()
def edit_artist(request, pk=None):
    """
    Either add a new Artist,
    or change an existing one
    """

    # Retrieve object
    if pk is None:
        # "Add" mode
        object = None
        required_permission = 'backend.add_artist'
    else:
        # "Change" mode
        object = get_object_by_uuid_or_404(Artist, pk)
        required_permission = 'backend.change_artist'

    # Check user permissions
    if not request.user.is_authenticated or not request.user.has_perm(required_permission):
        raise PermissionDenied


    # Either render only the modal content, or a full standalone page
    if is_ajax(request):
        template_name = 'frontend_forms/generic_form_inner.html'
    else:
        template_name = 'dialogs/generic_form.html'

    if request.method == 'POST':

        simulate_network_latency()

        form = ArtistEditForm(instance=object, data=request.POST)
        if form.is_valid():
            object = form.save()
            if not is_ajax(request):
                # reload the page
                if pk is None:
                    message = 'The object "%s" was added successfully.' % object
                else:
                    message = 'The object "%s" was changed successfully.' % object
                messages.success(request, message)
                next = request.META['PATH_INFO']
                return HttpResponseRedirect(next)
            # if is_ajax(), we just return the validated form, so the modal will close
    else:
        form = ArtistEditForm(instance=object)

    return render(request, template_name, {
        'form': form,
        'object': object,
    })


def delete_artist(request, pk):

    required_permission = 'backend.delete_artist'
    if not request.user.is_authenticated or not request.user.has_perm(required_permission):
        raise PermissionDenied

    object = get_object_by_uuid_or_404(Artist, pk)
    object_id = object.id
    object.delete()

    return JsonResponse({'object_id': object_id})


def new_track(request):

    simulate_network_latency()

    if is_ajax(request):
        template_name = 'dialogs/track_form_inner.html'
    else:
        template_name = 'dialogs/track_form.html'

    if request.method == 'POST':
        form = TrackForm(data=request.POST)
        if form.is_valid():
            #form.save()
            if not is_ajax(request):
                messages.info(request, "Form has been validated")
            else:
                return HttpResponse(
                    '<h1>Great !</h1> Your form has been validated<br /><br />You entered <b>"%s"</b>' % form.cleaned_data['name']
                )
    else:
        form = TrackForm()

    #action = request.get_full_path()

example/samples/templates/samples/advanced_form.html
{% extends "base.html" %}
{% load static i18n %}


{% block content %}
{% include 'samples/advanced_form_inner.html' %}
{% endblock content %}


{% block extrastyle %}
<style>
    form {
        max-width: 400px;
        border: 1px solid black;
        padding: 40px;
    }
</style>
{% endblock extrastyle %}


{% block extrajs %}
<script>
    $(document).ready(function() {
        $("form .datepicker").datepicker({});
    });
</script>
{% endblock extrajs %}

example/samples/templates/samples/edit_a_django_model_basic.html
{% extends "base.html" %}

{% block extrastyle %}
    <style>
        tr.selected { background-color: #ffff99 !important; }
    </style>
{% endblock extrastyle %}


{% block content %}
    <h1>Edit a Django Model</h1>

    <table>
        <tr>
            <td><a href="{% url 'samples:artist-add-basic' %}" class="btn btn-primary">Add</a></td>
            <td><p>Create an Artist (standalone form)</p></td>
        </tr>
    </table>
    <br />

    <h3>Artists</h3>
    <table class="table table-striped table-responsive">
        <thead class="thead-dark">
            <tr>
                <th>Name</th>
                <th>Notes</th>
                <th><a href="#" class="btn btn-primary" onclick="dialog_artist_add.open(event); return false;">Add</a></th>
            </tr>
        </thead>
        {% for artist in artists %}
            <tr class="{% if request.GET.selected_artist == artist.id|stringformat:'s' %}selected{% endif %}">
                <td>{{artist.name}}</td>
                <td>{{artist.notes|linebreaksbr}}</td>
                <td>
                    <a href="{% url 'samples:artist-change-basic' artist.id %}" class="btn btn-primary" onclick="open_artist_change_dialog(event); return false;">Edit</a>
                </td>
            </tr>
        {% endfor %}
    </table>

{% endblock content %}


{% block extrajs %}
<script language="javascript">


    function open_artist_change_dialog(event) {
        event.preventDefault();
        var url = $(event.target).attr('href');
        dialog_artist_change.options.url = url;
        dialog_artist_change.open(event);
    }


    $(document).ready(function() {

        dialog_artist_add = new Dialog({
            url: "{% url 'samples:artist-add-basic' %}",
            dialog_selector: '#dialog_generic',
            html: '<h1>Loading ...</h1>',
            width: '600px',
            min_height: '200px',
            title: '<i class="fa fa-calculator"></i> Create an Artist ...',
            button_save_initially_hidden: true,
            enable_trace: true,
            callback: function(event_name, dialog, params) {
                switch (event_name) {
                    case "submitting":
                        FrontendForms.overlay_show('.dialog-body');
                        break;
                    case "loaded":
                        FrontendForms.overlay_hide('.dialog-body');
                        break;
                    case "submitted":
                        var object_id = dialog.element.find('input[name=object_id]').val();
                        // Reload page, with last selection enhanced
                        var url = new URL(document.location.href);
                        url.searchParams.set('selected_artist', object_id);
                        FrontendForms.gotourl(url, show_layer=true);
                        break;
                }
            }
        });

        dialog_artist_change = new Dialog({
            url: "...",
            dialog_selector: '#dialog_generic',
            html: '<h1>Loading ...</h1>',
            width: '600px',
            min_height: '200px',
            title: '<i class="fa fa-calculator"></i> Update an Artist ...',
            button_save_initially_hidden: true,
            enable_trace: true,
            callback: function(event_name, dialog, params) {
                switch (event_name) {
                    case "submitting":
                        FrontendForms.overlay_show('.dialog-body');
                        break;
                    case "loaded":
                        FrontendForms.overlay_hide('.dialog-body');
                        break;
                    case "submitted":
                        var object_id = dialog.element.find('input[name=object_id]').val();
                        // Reload page, with last selection enhanced
                        var url = new URL(document.location.href);
                        url.searchParams.set('selected_artist', object_id);
                        FrontendForms.gotourl(url, show_layer=true);
                        break;
                }
            }
        });

    });

</script>
{% endblock extrajs %}

example/samples/templates/samples/edit_a_django_model_revised.html
{% extends "base.html" %}

{% block extrastyle %}
    <style>
        tr.selected { background-color: #ffff99 !important; }
        table a.btn { padding: 2px 8px; font-size: 12px; }
    </style>
{% endblock extrastyle %}


{% block content %}
    <h1>Edit a Django Model (Revised)</h1>

    <table>
        <tr>
            <td><a href="{% url 'samples:artist-add' %}" class="btn btn-primary">Add</a></td>
            <td><p>Create an Artist (standalone form)</p></td>
        </tr>
    </table>
    <br />

    <h3>Artists</h3>
    <table class="table table-striped table-responsive table-sm table-hover">
        <thead class="thead-dark">
            <tr>
                <th>Name</th>
                <th>Notes</th>
                <th><a href="{% url 'samples:artist-add' %}" class="btn btn-primary" onclick="open_artist_edit_dialog(event, 'Create an Artist ...'); return false;">Add</a></th>
            </tr>
        </thead>
        <tbody>
        {% for artist in artists %}
            <tr id="artist-{{artist.id}}" class="{% if request.GET.selected_record == artist.id|stringformat:'s' %}selected{% endif %}">
                <td>{{artist.name}}</td>
                <td>{{artist.notes|linebreaksbr}}</td>
                <td>
                    <a href="{% url 'samples:artist-change' artist.id %}" class="btn btn-primary" onclick="open_artist_edit_dialog(event); return false;">Edit</a>
                    <a href="{% url 'samples:artist-delete' artist.id %}" class="btn btn-danger" onclick="delete_artist(event, 'Deleting {{artist.name}}'); return false;">Delete</a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock content %}


{% block extrajs %}
<script language="javascript">


    function open_artist_edit_dialog(event, title) {
        event.preventDefault();
        var url = $(event.target).attr('href');
        dialog_edit.options.url = url;
        dialog_edit.options.title = title;
        dialog_edit.open(event);
    }

    function delete_artist(event, title) {
        event.preventDefault();
        var url = $(event.target).attr('href');
        FrontendForms.confirmRemoteAction(
            url,
            {
                title: title,
                text: 'Are you sure?',
                confirmButtonClass: 'btn-danger',
                icon: 'question'
            },
            function(data) {

                // FrontendForms.reload_page(true);
                var row = $('tr#artist-'+data.object_id);
                row.remove();

                Swal.fire({
                    text: 'Artist "' + data.object_id + '" has been deleted',
                    icon: 'warning'
                })
            },
            data=true   // set to any value to obtain POST
        );
    }


    $(document).ready(function() {

        dialog_edit = new Dialog({
            //url: "{% url 'samples:artist-add' %}",
            dialog_selector: '#dialog_generic',
            html: '<h1>Loading ...</h1>',
            width: '600px',
            min_height: '200px',
            //title: '<i class="fa fa-calculator"></i> Create an Artist ...',
            button_save_initially_hidden: true,
            enable_trace: true,
            callback: function(event_name, dialog, params) {
                switch (event_name) {
                    case "submitting":
                        FrontendForms.overlay_show('.dialog-body');
                        break;
                    case "loaded":
                        FrontendForms.overlay_hide('.dialog-body');
                        break;
                    case "submitted":
                        var object_id = dialog.element.find('input[name=object_id]').val();
                        // Reload page, with last selection enhanced
                        var url = new URL(document.location.href);
                        url.searchParams.set('selected_record', object_id);
                        FrontendForms.gotourl(url, show_layer=true);
                        break;
                }
            }
        });

    });

</script>
{% endblock extrajs %}

example/samples/templates/samples/form_advanced.html
{% extends "base.html" %}

{% block content %}
    <h1>Forms with advanced widgets</h1>
    <table>
        <tr>
            <td><a data-value="1" href="#" class="link-button btn btn-primary">Using select2</a></td>
            <td><p>A dialog with a form which uses select2</p></td>
        </tr>
        <tr>
            <td><a href="{% url 'samples:new-track' %}" class="btn btn-primary" target="_new">Using select2 (standalone page)</a></td>
            <td><p>The same form in a standalone page</p></td>
        </tr>
        <tr>
            <td><a href="{% url 'samples:new-track-ex' %}" class="btn btn-primary" target="_new">Replicating Django’s admin form popups</a></td>
        </tr>
    </table>
{% endblock content %}


{% block extrajs %}
<script language="javascript">


    function onLinkButtonClicked(event) {
        event.preventDefault();
        var n = $(event.target).data('value');
        var dialogs = [dialog1];
        dialogs[n - 1].open(event);
    }


    $(document).ready(function() {

        $('.link-button').on('click', onLinkButtonClicked);

        dialog1 = new Dialog({
            url: "{% url 'samples:new-track' %}",
            dialog_selector: '#dialog_generic',
            html: '<h1>Loading ...</h1>',
            width: '400px',
            min_height: '200px',
            title: '<i class="fa fa-calculator"></i> Edit a new track ...',
            button_save_initially_hidden: true,
            enable_trace: true,
            callback: function(event_name, dialog, params) {
                switch (event_name) {
                    case "loaded":
                        // "Select2 does not function properly when I use it inside a Bootstrap modal":
                        // https://select2.org/troubleshooting/common-problems#select2-does-not-function-properly-when-i-use-it-inside-a-bootst
                        $(dialog.element).find('.django-select2').djangoSelect2({
                            dropdownParent: dialog.element
                        });
                        break;
                }
            }
        });

    });

</script>
{% endblock extrajs %}

example/samples/templates/samples/simple_content2.html
{% extends "base.html" %}
{% load static i18n %}

{% block content %}
{% include 'samples/simple_content2_inner.html' %}
{% endblock content %}

example/samples/templates/samples/simple_dialogs.html
{% extends "base.html" %}

{% block content %}
    <h1>Simple Dialogs with Django</h1>

    <table>
        <tr>
            <td><a data-value="1" href="#" class="link-button btn btn-primary">dialog1</a></td>
            <td><p>A simple dialog with static content</p></td>
        </tr>
        <tr>
            <td><a data-value="2" href="#" class="link-button btn btn-primary">dialog2</a></td>
            <td><p>A dialog which closest itself</p></td>
        </tr>
        <tr>
            <td><a data-value="3" href="#" class="link-button btn btn-primary">dialog3</a></td>
            <td><p>A dialog whose content is obtained via an Ajax call</p></td>
        </tr>
        <tr>
            <td><a data-value="4" href="#" class="link-button btn btn-primary">dialog4</a></td>
            <td><p>A dialog who tries to load content via Ajax, but a server-side error occurs</p></td>
        </tr>
        <tr>
            <td><a data-value="5" href="#" class="link-button btn btn-primary">dialog5</a></td>
            <td><p>A dialog which renders a flexible view ...</p></td>
        </tr>
        <tr>
            <td><a href="{% url 'samples:simple-content2' %}" class="btn btn-primary">standalone page</a></td>
            <td><p>... which can also produce a standalone HTML page</p></td>
        </tr>
    </table>

{% endblock content %}


{% block extrajs %}
<script language="javascript">


    function onLinkButtonClicked(event) {
        event.preventDefault();
        var n = $(event.target).data('value');
        var dialogs = [dialog1, dialog2, dialog3, dialog4, dialog5];
        dialogs[n - 1].open(event);
    }


    $(document).ready(function() {

        $('.link-button').on('click', onLinkButtonClicked);

        dialog1 = new Dialog({
            dialog_selector: '#dialog_generic',
            html: '<h1>Static content goes here ...</h1>',
            width: '600px',
            min_height: '200px',
            title: '<i class="fa fa-calculator"></i> Select an object ...',
            footer_text: 'testing dialog ...',
            enable_trace: true
        });

        function dialog2_callback(event_name, dialog, params) {
            switch (event_name) {
                case "created":
                    console.log('Dialog created: dialog=%o, params=%o', dialog, params);
                    break;
                case "shown":
                    setTimeout(function() {
                        dialog.close();
                    }, 3000);
                    break;
            }
        }

        dialog2 = new Dialog({
            dialog_selector: '#dialog_generic',
            html: '<h1>Will close in a few seconds ...</h1>',
            width: '400px',
            min_height: '200px',
            title: '<i class="fa fa-calculator"></i> Select an object ...',
            button_save_label: null,
            enable_trace: true,
            callback: dialog2_callback
        });

        dialog3 = new Dialog({
            url: "{% url 'samples:simple-content' %}",
            dialog_selector: '#dialog_generic',
            html: '<h1>Loading ...</h1>',
            width: '400px',
            min_height: '200px',
            title: '<i class="fa fa-calculator"></i> Select an object ...',
            button_save_label: null,
            enable_trace: true
        });

        dialog4 = new Dialog({
            url: "{% url 'samples:simple-content-forbidden' %}",
            dialog_selector: '#dialog_generic',
            html: '<h1>Loading ...</h1>',
            width: '400px',
            min_height: '200px',
            title: '<i class="fa fa-calculator"></i> Select an object ...',
            button_save_label: null,
            enable_trace: true
        });

        dialog5 = new Dialog({
            url: "{% url 'samples:simple-content2' %}",
            dialog_selector: '#dialog_generic',
            html: '<h1>Loading ...</h1>',
            width: '800px',
            min_height: '200px',
            title: '<i class="fa fa-calculator"></i> Select an object ...',
            button_save_label: null,
            enable_trace: true
        });

        //dialog1.open();

    });

</script>
{% endblock extrajs %}

example/samples/templates/samples/simple_form.html
{% extends "base.html" %}
{% load static i18n %}

{% block content %}
{% include 'samples/simple_form_inner.html' %}
{% endblock content %}

{% block extrastyle %}
<style>
    form {
        max-width: 400px;
        border: 1px solid black;
        padding: 40px;
    }
</style>
{% endblock extrastyle %}

example/samples/templates/samples/simple_form_with_addon.html
{% extends "base.html" %}
{% load static i18n %}

{% block content %}
{% include 'samples/simple_form_inner_with_addon.html' %}
{% endblock content %}

{% block extrastyle %}
<style>
    form {
        max-width: 400px;
        border: 1px solid black;
        padding: 40px;
    }
</style>
{% endblock extrastyle %}